import { FeedPost } from './types'

export const SEED_POSTS: FeedPost[] = [
  {
    id: 'seed-1',
    user_id: 'seed-user-1',
    content_type: 'chat',
    x_description: "trying to build an app and realizing mid-conversation he didn't know what he was actually building",
    moments: [
      "Nah the solo value is ChatGPT or Claude right",
      "Okay stop you're just asking me more questions",
      "this is not an AI app at all. so it's just about sharing",
      "Not young adults specific",
      "High concept I know",
    ],
    artifact_url: null,
    created_at: new Date(Date.now() - 5 * 60000).toISOString(),
    handle: 'aj',
    name: 'Aditya',
    avatar_initials: 'AJ',
    school: 'NYU',
    like_count: 24,
    reply_count: 3,
  },
  {
    id: 'seed-2',
    user_id: 'seed-user-2',
    content_type: 'image',
    x_description: "what her apartment would look like if it reflected who she actually is, not who she's trying to be",
    moments: [
      "I keep pinning things I don't actually like",
      "I want it to feel like I live there alone for the first time",
      "make it look a little bit sad but in a good way",
      "not staged for anyone else",
      "warm and a little melancholy",
    ],
    artifact_url: null,
    created_at: new Date(Date.now() - 2 * 3600000).toISOString(),
    handle: 'sara',
    name: 'Sara',
    avatar_initials: 'SR',
    school: null,
    like_count: 41,
    reply_count: 1,
  },
  {
    id: 'seed-3',
    user_id: 'seed-user-3',
    content_type: 'voice',
    x_description: "switching his major junior year and what he's actually afraid of",
    moments: [
      "my parents are going to lose it",
      "I've been good at things I don't care about my whole life",
      "what if I'm bad at the thing I actually want",
      "I think I've been waiting for someone to tell me it's okay",
      "I don't know what I'm doing but I know I have to do it",
    ],
    artifact_url: null,
    created_at: new Date(Date.now() - 5 * 3600000).toISOString(),
    handle: 'marcus',
    name: 'Marcus',
    avatar_initials: 'MK',
    school: null,
    like_count: 67,
    reply_count: 7,
  },
  {
    id: 'seed-4',
    user_id: 'seed-user-4',
    content_type: 'doc',
    x_description: "writing an email to her professor she's been putting off for three weeks",
    moments: [
      "I don't know why I'm so scared of this",
      "make it sound confident even though I'm not",
      "actually no that sounds too formal I don't talk like that",
      "okay that one. that's the one.",
      "it's a three-sentence email and I've been avoiding it for weeks",
    ],
    artifact_url: null,
    created_at: new Date(Date.now() - 8 * 3600000).toISOString(),
    handle: 'priya',
    name: 'Priya',
    avatar_initials: 'PL',
    school: null,
    like_count: 19,
    reply_count: 2,
  },
]

export const SEED_REPLIES: Record<string, FeedPost[]> = {
  'seed-1': [
    {
      id: 'reply-1',
      user_id: 'seed-user-2',
      content_type: 'chat',
      x_description: "whether she's been building things for other people her whole life",
      moments: [],
      artifact_url: null,
      created_at: new Date(Date.now() - 1 * 3600000).toISOString(),
      handle: 'sara',
      name: 'Sara',
      avatar_initials: 'SR',
      school: null,
      like_count: 8,
      reply_count: 0,
    },
    {
      id: 'reply-2',
      user_id: 'seed-user-3',
      content_type: 'chat',
      x_description: "how often he starts things without knowing why",
      moments: [],
      artifact_url: null,
      created_at: new Date(Date.now() - 2 * 3600000).toISOString(),
      handle: 'marcus',
      name: 'Marcus',
      avatar_initials: 'MK',
      school: null,
      like_count: 5,
      reply_count: 0,
    },
    {
      id: 'reply-3',
      user_id: 'seed-user-4',
      content_type: 'chat',
      x_description: "the difference between not knowing and being afraid to know",
      moments: [],
      artifact_url: null,
      created_at: new Date(Date.now() - 3 * 3600000).toISOString(),
      handle: 'priya',
      name: 'Priya',
      avatar_initials: 'PL',
      school: null,
      like_count: 12,
      reply_count: 0,
    },
  ],
}
